# Exercises

### #1 - Calculate the BMI (body mass index) on the two lists below using NDArrays...

In [ ]:
import numpy as np
# formula = weight / (height**2) * 730
height = [69, 70, 71, 72, 73, 74, 75]
weight = [110, 120, 130, 140, 150, 160, 170]

# OUTPUT: [16.86620458 17.87755102 18.82562984 19.71450617 20.54794521 21.32943755
# 22.06222222]

np_height = np.array(height)
np_weight = np.array(weight)

print(type(np_height))

bmi = np_weight / np_height ** 2
print(bmi)


### #2 - Create a function that will take in two parameters and will create a random matrix based off of those parameters. Extra: Have additional parameters taken in that allow the user to choose the shape and data type of the matrix.

In [2]:
import numpy as np 

somematrixarray = np.random.randint(2, 5, size=(3,4))

print(somematrixarray)

"""
Example Result
array([[14.21633515,  7.98846653,  9.64140715],
       [ 6.30982234,  9.96414331,  8.43153688],
       [14.73102068, 11.76072894, 14.23356121]])
"""


[[2 4 2 3]
 [4 3 2 2]
 [4 2 2 3]]


'\nExample Result\narray([[14.21633515,  7.98846653,  9.64140715],\n       [ 6.30982234,  9.96414331,  8.43153688],\n       [14.73102068, 11.76072894, 14.23356121]])\n'

### #3 - Open and load the data in the two text files that have the Boston Red Sox hitting data for the past seasons. Compare the difference in the two years by putting the data into an NDArray and running a differencial operation on it. The column to look for will be SLG.

Your output should display which year (either 2017 or 2018) was a better year based on SLG

In [11]:
import csv
import numpy as np

In [12]:
"""
Example Result - Not the actual result
Boston 18 had more SLG in 2018
[0.404 0.443 0.392 0.403 0.482 0.424 0.402 0.459 0.429 0.354 0.387 0.333
 0.539 0.243 0.262 0.354 0.342 0.339 0.328 0.306 0.222 0.2   1.   ]
"""

FIELDS = ['Rk', 'Pos', 'Name', 'Age', 'G', 'PA', 'AB', 'R', 'H', '2B', '3B', 'HR', 'RBI', 'SB', 'CS', 
          'BB', 'SO', 'BA', 'OBP', 'SLG', 'OPS', 'OPS+', 'TB', 'GDP', 'HBP', 'SH', 'SF', 'IBB']

DATATYPES = [('rk', 'i'), ('pos', '|S25'), ('name', '|S25'), ('age', 'i'), ('g', 'i'), ('pa', 'i'), ('ab', 'i'),
                ('r', 'i'), ('h', 'i'), ('2b', 'i'), ('3b', 'i'), ('hr', 'i'), ('rbi', 'i'), ('sb', 'i'), ('cs', 'i'),
                ('bb', 'i'), ('so', 'i'), ('ba', 'f'), ('obp', 'f'), ('slg', 'f'), ('ops', 'f'), ('opsp', 'i'),
                ('tb', 'i'), ('gdp', 'i'), ('hbp', 'i'), ('sh', 'i'), ('sf', 'i'), ('ibb', 'i')]

#Use this function to actually open the data inside of a NDArray
def better_year(cat):
    return """
Example Result - Not the actual result
Boston 18 had more SLG in 2018
[0.404 0.443 0.392 0.403 0.482 0.424 0.402 0.459 0.429 0.354 0.387 0.333
 0.539 0.243 0.262 0.354 0.342 0.339 0.328 0.306 0.222 0.2   1.   ]
"""

better_year('SLG')


'\nExample Result - Not the actual result\nBoston 18 had more SLG in 2018\n[0.404 0.443 0.392 0.403 0.482 0.424 0.402 0.459 0.429 0.354 0.387 0.333\n 0.539 0.243 0.262 0.354 0.342 0.339 0.328 0.306 0.222 0.2   1.   ]\n'

In [13]:
def get_data(filename, delimiter= ','):
    data = np.genfromtxt(filename, delimiter=delimiter, skip_header=1, names=FIELDS, dtype=DATATYPES)
    return data

def whosbetter(category):
    bs2017 = get_data('../redsox_2017_hitting.txt')
    bs2018 = get_data('../redsox_2018_hitting(1).txt')
    bs2017_cat = sum(bs2017[category])
    bs2018_cat = sum(bs2018[category])
    if bs2017_cat > bs2018_cat: 
        return f"Boston '17 had more {category} by {bs2017_cat-bs2018_cat}"
    else:
        return f"Boston '18 had more {category} by {bs2018_cat-bs2017_cat}"
    
print(whosbetter('SLG'))

FileNotFoundError: [Errno 2] No such file or directory: '../redsox_2017_hitting.txt'